<%@ page trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="cms" uri="http://hybris.com/tld/cmstags"%>

<c:if test="${component.visible}">
	<nav class="navigation navigation--bottom navigation-menu js_navigation--bottom js-enquire-offcanvas-navigation" role="navigation">
		<ul class="sticky-nav-top hidden-lg hidden-md js-sticky-user-group hidden-md hidden-lg">
                <%--Dynamically generated by 'acc.navigation.js"--%>
        </ul>
		<div class="navigation__overflow">
			<ul data-trigger="#signedInUserOptionsToggle" class="nav__links nav__links--products nav__links--mobile js-userAccount-Links js-nav-collapse-body offcanvasGroup1 collapse in hidden-md hidden-lg">
                   <%--Dynamically generated by 'acc.navigation.js"--%>
           	</ul>
           	<ul class="nav__links nav__links--products js-offcanvas-links nav-categories">
				<c:forEach items="${component.navigationNode.children}" var="childLevel1"> 
					<li class="auto nav__links--primary <c:if test="${not empty childLevel1.children}">nav__links--primary-has__sub js-enquire-has-sub nav-category-drop</c:if> nav-category-1">
						<c:forEach items="${childLevel1.entries}" var="childlink1">
							<cms:component component="${childlink1.item}" evaluateRestriction="true" element="span" class="nav__link js_nav__link category-1-link" />
						</c:forEach>
						
						<%-- Calculate how many sub columns are needed -- Start --%>
						<c:set var="totalSubNavigationColumns" value="${0}"/>
						<c:set var="hasSubChild" value="false"/>
						<c:forEach items="${childLevel1.children}" var="childLevel2"> 
							<c:if test="${not empty childLevel2.children}">
								<c:set var="hasSubChild" value="true"/>
								<c:set var="subSectionColumns" value="${fn:length(childLevel2.children)/component.wrapAfter}"/>
								<c:if test="${subSectionColumns > 1 && fn:length(childLevel2.children)%component.wrapAfter > 0}">
									<c:set var="subSectionColumns" value="${subSectionColumns + 1}"/>
								</c:if>
								<c:choose>
									<c:when test="${subSectionColumns > 1}">
										<c:set var="totalSubNavigationColumns" value="${totalSubNavigationColumns + subSectionColumns}" />
									</c:when>
			
									<c:when test="${subSectionColumns < 1}">
										<c:set var="totalSubNavigationColumns" value="${totalSubNavigationColumns + 1}" />
									</c:when>
								</c:choose>
							</c:if>
						</c:forEach>
						<%-- Calculate how many sub columns are needed -- End --%>
						
						<c:if test="${not empty childLevel1.children}"><span class="hidden-md hidden-lg nav__link--drill__down js_nav__link--drill__down"><i class="fa fa-angle-right"></i></span>
							<div class="sub__navigation js_sub__navigation navigation-container category-drop-box">
								<a class="sm-back js-enquire-sub-close hidden-md hidden-lg" href="#">Back</a>
								<div class="row navigation-container-child category-drop-sub-box">
									<c:choose>
									    <c:when test="${hasSubChild}">
									        <c:forEach items="${childLevel1.children}" var="childLevel2"> 
												<div class="sub-navigation-section nav-category-2">
													<c:if test="${not empty childLevel2.title}">
														<a href="${fn:escapeXml(childLevel2.title)}"><div class="title category-2-link">${fn:escapeXml(childLevel2.title)}</div></a>
														
													</c:if>
													<ul class="sub-navigation-list nav-category-3 <c:if test="${not empty childLevel2.title}">has-title</c:if>">
														<c:forEach items="${childLevel2.children}" var="childLevel3" step="${component.wrapAfter}" varStatus="i">
															<%-- wrap if more than 'component.wrapAfter' rows in one sub column --%>
															<c:if test="${i.index>=component.wrapAfter}"> 
																<c:if test="${!i.first}">
																		</ul>
																	</div>
																</c:if>
																<div class="sub-navigation-section">
																	<ul class="sub-navigation-list <c:if test="${not empty childLevel2.title}">has-title</c:if>">
															</c:if>
															<c:forEach items="${childLevel2.children}" var="childLevel3" begin="${i.index}" end="${i.index + component.wrapAfter - 1}">
																<c:forEach items="${childLevel3.entries}" var="childlink3" >
																	<cms:component component="${childlink3.item}" evaluateRestriction="true" element="li" class="nav__link--secondary category-3-link" />
																</c:forEach>
															</c:forEach>
														</c:forEach>
													</ul>
												</div>	
											</c:forEach>
									    </c:when>    
									    <c:otherwise>
									    	<div class="sub-navigation-section nav-category-2">
									    		<ul class="sub-navigation-list <c:if test="${not empty childLevel2.title}">has-title</c:if> nav-category-3">
										        	<c:forEach items="${childLevel1.children}" var="childLevel2"> 
														<c:forEach items="${childLevel2.entries}" var="childlink2">
															<cms:component component="${childlink2.item}" evaluateRestriction="true" element="li" class="nav__link--secondary category-3-link" />
														</c:forEach>
													</c:forEach>
												</ul>
											</div>	
									    </c:otherwise>
									</c:choose>
								</div>
							</div>
						</c:if>
					</li>
				</c:forEach>
			</ul>
		</div>
	</nav>
</c:if>